meta_title: "Phasme Music -  French electronic music duo"
meta_description: "Phasme is a French electronic music duo formed by Elliot Bluche and Jules Lemer. Both born in Nantes 7 days apart, they became best friends from the day they could talk."
meta_image: "Phasme.gif" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
